# Generated by Django 4.0.6 on 2023-03-19 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadview', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='files',
            new_name='files1',
        ),
    ]
