# Generated by Django 4.0.6 on 2023-03-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadview', '0002_rename_files_files1'),
    ]

    operations = [
        migrations.AddField(
            model_name='files1',
            name='name',
            field=models.CharField(default='demo file', max_length=255),
        ),
    ]
