# Generated by Django 4.0.6 on 2023-03-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadview', '0003_files1_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files1',
            name='name',
            field=models.CharField(blank=True, default='demo file', max_length=255, null=True),
        ),
    ]
