# Generated by Django 4.0.6 on 2023-03-21 18:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leadview', '0004_alter_files1_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='files1',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
