# Generated by Django 4.0.6 on 2023-05-12 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadview', '0007_video_delete_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='video',
        ),
    ]
