# Generated by Django 4.0.6 on 2023-04-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresherview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='link',
            field=models.CharField(default='hi', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='name',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
