# Generated by Django 4.0.6 on 2023-04-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresherview', '0002_quiz_link_quiz_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='link',
            new_name='link_quiz',
        ),
        migrations.AddField(
            model_name='quiz',
            name='link_answer',
            field=models.CharField(default='1', max_length=500),
            preserve_default=False,
        ),
    ]
