# Generated by Django 4.0.6 on 2023-04-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresherview', '0003_rename_link_quiz_link_quiz_quiz_link_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='duration',
            field=models.IntegerField(default=5, help_text='Enter the duration in minutes'),
            preserve_default=False,
        ),
    ]
