# Generated by Django 4.0.6 on 2023-04-20 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0022_project_files'),
        ('fresherview', '0005_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee_information.department'),
            preserve_default=False,
        ),
    ]
