# Generated by Django 4.0.6 on 2022-12-10 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0007_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='project_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee_information.project'),
            preserve_default=False,
        ),
    ]
