# Generated by Django 4.0.6 on 2022-12-12 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0008_employees_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_lead',
            field=models.CharField(default='carie', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
