# Generated by Django 4.0.6 on 2022-12-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0009_project_project_lead_project_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='project_lead',
            field=models.BooleanField(default=False),
        ),
    ]
