# Generated by Django 4.0.6 on 2022-12-12 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0010_employees_project_lead'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='project_lead',
            new_name='lead',
        ),
    ]
