# Generated by Django 4.0.6 on 2023-02-26 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0012_employees_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='project_id',
        ),
    ]
