# Generated by Django 4.0.6 on 2023-03-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0016_notification_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
