# Generated by Django 4.0.6 on 2023-03-14 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0017_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='task_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee_information.task'),
            preserve_default=False,
        ),
    ]
