# Generated by Django 4.0.6 on 2023-03-14 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0018_employees_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='task_id',
        ),
    ]
