# Generated by Django 4.0.6 on 2023-03-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0019_remove_employees_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='employeetype',
            field=models.TextField(blank=True, null=True),
        ),
    ]
