# Generated by Django 4.0.6 on 2023-03-17 08:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0020_employees_employeetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee_information.employees'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employees',
            name='employeetype',
            field=models.TextField(default='Employee'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
