# Generated by Django 4.0.6 on 2023-03-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0021_task_assigned_alter_employees_employeetype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
