# Generated by Django 4.0.6 on 2023-05-16 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0027_alter_attendance_intime_alter_attendance_outime'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
    ]
