# Generated by Django 4.0.6 on 2023-05-16 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0028_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee_id', 'date')},
        ),
    ]
