# Generated by Django 4.0.6 on 2023-05-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0029_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Excused', 'Excused'), ('Not a Working Day', 'Not a Working Day')], default='Absent', max_length=20),
        ),
    ]
